---
# tasks file for ansible-role-vim.

- name: Perform package install and removal for Vim and Vim plugin install.
  when: "vim_manage_packages|bool == true"
  ansible.builtin.include_tasks: "manage-packages.yml"

- name: Perform setup tasks for Vim and Vim plugin install.
  ansible.builtin.include_tasks: "setup.yml"

- name: Perform dotfile installation for Vim.
  ansible.builtin.include_tasks: "copy-dotfiles.yml"

- name: Perform Vim plugin installation.
  ansible.builtin.include_tasks: "install-plugin.yml"
  loop: "{{ vim_installed_plugins }}"
  loop_control:
    loop_var: vim_plugin_install

- name: Perform Vim plugin helpdoc build.
  ansible.builtin.include_tasks: "build-helpdocs.yml"
  loop: "{{ vim_installed_plugins }}"
  loop_control:
    loop_var: vim_plugin_helpdoc

- name: Perform Vim plugin removal.
  ansible.builtin.include_tasks: "remove-plugin.yml"
  loop: "{{ vim_removed_plugins }}"
  loop_control:
    loop_var: vim_plugin_remove
